services:
  back-end:
    hostname: back-end
    build:
      context: .
      dockerfile: ./back-end/Dockerfile
    restart: on-failure
    depends_on:
      - mysql
    volumes:
      - ./back-end:/home/root/app
      - private_node_modules:/home/root/app/node_modules
    ports:
      - 3000:3000
    env_file:
      - ./back-end/.env
    networks:
      - internal

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword   
      MYSQL_DATABASE: laravel                                
      MYSQL_PASSWORD:           
    ports:
      - "3306:3306"  
    volumes:
      - mysql_data:/var/lib/mysql   

  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - "16686:16686"  # UI
      - "4317:4317"    # OTLP/gRPC
      - "4318:4318"    # OTLP/HTTP
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  mysql_data:
  private_node_modules:
